### ISSUE TITLE
Menu item is undefined in models/menu::getMenuModel

### ISSUE THREAD

**Issue by philbooth** [philbooth/JSComplexity.org#4]
Raised initially here:

https://github.com/philbooth/complexity-report/issues/43

This is the stack trace:

```
GET / 500 2ms
TypeError: Cannot call method 'trim' of undefined
    at Object.menu (/mnt/data/1/models/menu.js:9:32)
    at Object.Hogan.Template.ms (/mnt/data/1/node_modules/hogan-express/node_modules/hogan.js/lib/template.js:226:25)
    at Object.Hogan.Template.s (/mnt/data/1/node_modules/hogan-express/node_modules/hogan.js/lib/template.js:124:20)
    at Object.eval [as r] (eval at <anonymous> (/mnt/data/1/node_modules/hogan-express/node_modules/hogan.js/lib/compiler.js:293:21), <anonymous>:2:252)
    at Object.Hogan.Template.ri (/mnt/data/1/node_modules/hogan-express/node_modules/hogan.js/lib/template.js:46:19)
    at Object.Hogan.Template.rp (/mnt/data/1/node_modules/hogan-express/node_modules/hogan.js/lib/template.js:96:22)
    at Object.eval [as r] (eval at <anonymous> (/mnt/data/1/node_modules/hogan-express/node_modules/hogan.js/lib/compiler.js:293:21), <anonymous>:2:995)
    at Object.Hogan.Template.ri (/mnt/data/1/node_modules/hogan-express/node_modules/hogan.js/lib/template.js:46:19)
    at Object.render (/mnt/data/1/node_modules/hogan-express/node_modules/hogan.js/lib/template.js:41:19)
    at /mnt/data/1/node_modules/hogan-express/hogan-express.js:167:29
```

This is the hack I've patched it with for now:

https://github.com/philbooth/JSComplexity.org/commit/a4dfde0be04606a1c790e63ff1df7d1409f72c57

The question is, why is `menuitem` undefined?

**Comment by philbooth** [comment]
Unfortunately I've stopped maintaining escomplex, so this issue will not get addressed by me. I'm not actively using the project myself any more and my attention is currently elsewhere so I can't give it the time it requires.

If anyone out there is interested in taking the project forward, they should definitely get in touch with me so we can chat and sort it out.

I'm adding this note to all open issues and have added a similar note to the readme, just to let people know. Sorry for the inconvenience. :)
